"""Initial migration - current database state

Revision ID: 613908a56b23
Revises: 
Create Date: 2025-11-18 19:54:10.326328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '613908a56b23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_analysis_history_confidence'), table_name='analysis_history')
    op.drop_index(op.f('idx_analysis_history_created'), table_name='analysis_history')
    op.drop_index(op.f('idx_analysis_history_fixture'), table_name='analysis_history')
    op.alter_column('fixtures', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('fixtures', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_fixtures_kickoff'), table_name='fixtures')
    op.drop_index(op.f('idx_fixtures_season_week'), table_name='fixtures')
    op.drop_index(op.f('idx_fixtures_status'), table_name='fixtures')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_fixtures_status'), 'fixtures', ['status'], unique=False)
    op.create_index(op.f('idx_fixtures_season_week'), 'fixtures', ['season', 'week'], unique=False)
    op.create_index(op.f('idx_fixtures_kickoff'), 'fixtures', ['kickoff_time'], unique=False)
    op.alter_column('fixtures', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('fixtures', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.create_index(op.f('idx_analysis_history_fixture'), 'analysis_history', ['fixture_id'], unique=False)
    op.create_index(op.f('idx_analysis_history_created'), 'analysis_history', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_analysis_history_confidence'), 'analysis_history', [sa.literal_column('confidence_score DESC')], unique=False)
    # ### end Alembic commands ###
